### ISSUE TITLE
how to play the game? can't figure it out

### ISSUE THREAD

**Issue by grandpa1946** [burntcustard/tiny-yurts#5]

**Comment by burntcustard** [comment]
Hi! Is there a particular part that you're struggling to understand, or that isn't working for you?

Perhaps seeing this play-through would make things clearer: [https://www.youtube.com/watch?v=Dhlqip9DtGA](https://www.youtube.com/watch?v=Dhlqip9DtGA)

Alternatively, the [How to play](https://github.com/burntcustard/tiny-yurts#how-to-play) or [Tips & Tricks](https://github.com/burntcustard/tiny-yurts#tips--tricks) sections of the [README](https://github.com/burntcustard/tiny-yurts#readme) might help?

**Comment by grandpa1946** [comment]
thanks! the walkthrough helped, what i didn't know was the goal of the game
